cluster_name: adversarial-policies
min_workers: 0
max_workers: 0
initial_workers: 0
target_utilization_fraction: 0.8
idle_timeout_minutes: 5

docker:
  image: humancompatibleai/adversarial_policies:latest
  container_name: ray
  run_options:
    # NOTE: MUJOCO_KEY must be set in environment (it is in our AMI)
    - "--env MUJOCO_KEY=${MUJOCO_KEY}"
    # Open port 6006 for TensorBoard
    - "-p 6006:6006"

provider:
    type: local
    head_ip: YOUR HOSTNAME
    worker_ips:
        - HOSTNAME 1
        - HOSTNAME 2

auth:
    ssh_user: YOUR USERNAME
    ssh_private_key: ~/.ssh/id_rsa

head_node: {}
worker_nodes: {}

# List of shell commands to run to set up nodes.
initialization_commands: []  # before entering Docker
setup_commands: []
head_setup_commands: []
worker_setup_commands: []
head_start_ray_commands:
    - >
      git remote set-url origin https://github.com/HumanCompatibleAI/adversarial-policies.git &&
      git pull &&
      env=modelfree . /adversarial-policies/ci/prepare_env.sh &&
      pip install . &&
      ray stop &&
      ulimit -n 65536 &&
      ray start --head --redis-port=6379 --object-manager-port=8076 --autoscaling-config=~/ray_bootstrap_config.yaml
worker_start_ray_commands:
    - >
      git remote set-url origin https://github.com/HumanCompatibleAI/adversarial-policies.git &&
      git pull &&
      env=modelfree . /adversarial-policies/ci/prepare_env.sh &&
      pip install . &&
      ray stop &&
      ulimit -n 65536 &&
      ray start --redis-address=$RAY_HEAD_IP:6379 --object-manager-port=8076
